#ifndef LIBAV_CONFIG_H
#define LIBAV_CONFIG_H

#define LIBAV_CONFIGURATION ""
#define LIBAV_LICENSE "LGPL version 2.1 or later"

#define CONFIG_FILE_PROTOCOL 1
#define CONFIG_HEVC_DECODER 1
#define CONFIG_HEVC_PARSER 1
#define CONFIG_DSPUTIL 1
#define ARCH_ARM 0
#define CONFIG_LATM_DEMUXER 0

#define HAVE_ATOMICS_NATIVE 1
#define HAVE_THREADS 1
#define HAVE_PTHREADS 0
#define HAVE_W32THREADS 1
#define HAVE_ATOMICS_GCC 0
#define HAVE_ATOMICS_SUNCC 0
#define HAVE_ATOMICS_WIN32 1

// MMX
#define ARCH_X86 1
#define ARCH_X86_32 0
#define ARCH_X86_64 1

#define HAVE_MMX_EXTERNAL 1
#define HAVE_SSE_EXTERNAL 1
#define HAVE_SSE2_EXTERNAL 1
#define HAVE_SSE3_EXTERNAL 1
#define HAVE_SSE4_EXTERNAL 1
#define HAVE_SSE42_EXTERNAL 1
#define HAVE_SSSE3_EXTERNAL 1
#define HAVE_MMXEXT_EXTERNAL 1
#define HAVE_AVX_EXTERNAL 1

#endif
